### ISSUE TITLE
IllegalStateException at the end of CEP test

### ISSUE THREAD

**Issue by debelyoo** [ottogroup/flink-spector#59]
I get the below exception at the end of my test. The test completes successfully though.
Why is that ?

java.lang.IllegalStateException: cannot enqueue after timer shutdown
	at akka.actor.LightArrayRevolverScheduler.scheduleOnce(LightArrayRevolverScheduler.scala:137)
	at akka.actor.Scheduler$class.scheduleOnce(Scheduler.scala:126)
	at akka.actor.LightArrayRevolverScheduler.scheduleOnce(LightArrayRevolverScheduler.scala:37)
	at akka.pattern.PromiseActorRef$.apply(AskSupport.scala:602)
	at akka.pattern.GracefulStopSupport$class.gracefulStop(GracefulStopSupport.scala:48)
	at akka.pattern.package$.gracefulStop(package.scala:41)
	at akka.pattern.Patterns$.gracefulStop(Patterns.scala:229)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster$$anonfun$4$$anonfun$apply$1.apply(FlinkMiniCluster.scala:432)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster$$anonfun$4$$anonfun$apply$1.apply(FlinkMiniCluster.scala:432)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster$$anonfun$4.apply(FlinkMiniCluster.scala:432)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster$$anonfun$4.apply(FlinkMiniCluster.scala:432)
	at scala.Option.map(Option.scala:146)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster.shutdown(FlinkMiniCluster.scala:431)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster.stop(FlinkMiniCluster.scala:410)
	at org.apache.flink.test.util.TestBaseUtils.stopCluster(TestBaseUtils.java:208)
	at io.flinkspector.core.runtime.Runner.shutdownLocalCluster(Runner.java:134)
	at io.flinkspector.core.runtime.Runner.cleanUp(Runner.java:176)
	at io.flinkspector.core.runtime.Runner.executeTest(Runner.java:219)
	at io.flinkspector.datastream.DataStreamTestEnvironment.executeTest(DataStreamTestEnvironment.java:79)
	at io.flinkspector.datastream.DataStreamTestBase.executeTest(DataStreamTestBase.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

My test
```scala
@Test
  def testWithFlinkspectorAndJavaStreams(): Unit = {
    val event1 = Event("xxx", "", "message")
    val event2 = Event("xxx", "", "web portal")
    val event3 = Event("xxx", "", "message")
    val event4 = Event("xxx", "", "message")
    val event5 = Event("xxx", "", "call")

    val input = createTimedTestStreamWith(event1).emit(event2).emit(event3).emit(event4).emit(event5).close()

    val pattern = Pattern.begin("event0").subtype(classOf[Event]).where(new EventActionCondition("message")).next("event1").where(new EventActionCondition("call"))

    val patternStream = CEP.pattern(input, pattern)
    val alertStream: DataStream[StreamAlert] = patternStream.select(new AlertPatternSelectFunction())

    val output: ExpectedRecords[StreamAlert] = ExpectedRecords.create(StreamAlert(2, "message", "call", "xxx", ""))

    assertStream(alertStream, output)
  }
```
And the util classes
```scala
class EventActionCondition(action: String) extends IterativeCondition[Event] {
  override def filter(value: Event, ctx: IterativeCondition.Context[Event]): Boolean = {
    value.action == action
  }
}
```
```scala
class AlertPatternSelectFunction extends PatternSelectFunction[Event, StreamAlert] {
  override def select(pattern: util.Map[String, util.List[Event]]): StreamAlert = {
    val event0 = pattern.get("event0").get(0)
    val event1 = pattern.get("event1").get(0)
    StreamAlert(pattern.size(), event0.action, event1.action, event0.user, event0.time)
  }
}
```
```scala
case class StreamAlert(nbOfEvents: Int, firstAction: String, lastAction: String, user: String, lastActionTime: String)
```

**Comment by lofifnc** [comment]
Do you get this exception with every run of the test?

Currently the LocalFlinkCluster will get shut down after every test. Flink seems to have registered some timer/scheduler with Akka internally. Which is now complaining because the ActorSystem gets shutdown and has still an active timer. I've never seen this exception but I think It can be ignored. I will catch this exception in the Future.

**Comment by debelyoo** [comment]
Yes, I get it with every run of the test

**Comment by lofifnc** [comment]
Ok, I'm going to have a detailed look into this on the weekend. The fix should be part of the release planned on monday.

**Comment by lofifnc** [comment]
I'm unable to reproduce this error. I will catch it but it would be interesting to see where this comes from. What Flink version are you using?

**Comment by debelyoo** [comment]
I'm using Flink 1.3.1, and Akka 2.4.16

**Comment by lofifnc** [comment]
I'm still unable to reproduce this. Nonetheless I've included a fix in the latest 0.8.1 release.
Could you test this and provide feedback if this resolves you problem?

**Comment by debelyoo** [comment]
I tested with release 0.8.1, but the exception still occurs.

However, the exception is not linked to flinkspector. I investigated a bit more, and this exception is actually linked to the Kafka version. Flink uses its own version of akka (forked from akka 2.3.X). I'm using version 2.4.19 and the exception seems to come from a library version conflict. I tested with akka 2.3.9 and the test completes without any exception.

Thanks for your time investigating anyway !

**Comment by whipit** [comment]
I am running flink version 1.4.1 with flink spector 0.8.1.   And I do get this exception.

@debelyoo -- "...I investigated a bit more, and this exception is actually linked to the **Kafka** version."   Do you mean Akka version here?

**Comment by lofifnc** [comment]
I think Akka version is meant. Are you using your own Akka dependency? Or maybe another dependency is using a different Akka version than Flink.
Could you also try using flink spector version 0.8.3?

**Comment by whipit** [comment]
AFAIK, I don't explicitly rely on Akka...and the only thing using akka is Flink.  

So I just downgraded to flink version 1.3.2 where the issue does not occur.   I'll try upgrading and retrying with flinkspector 0.8.3.

FWIW - I also added this SO question:  https://stackoverflow.com/questions/49012005/flink-cluster-throws-illegalstateexception-cannot-enqueue-after-timer-shutdown

I referenced this issue in the question.  The problem seems to impact some other areas too, so would be good to find out how to resolve long term.

**Comment by whipit** [comment]
Upgrading to flinkspector 0.8.3 with flink 1.4.1 seems to have fixed it.   I have not been able to reproduce the issue.  Here's my complete gradle dependency settings

```
    testCompile group: 'io.flinkspector', name: 'flinkspector-datastream_2.11', version: '0.8.3'
    compile group: 'org.apache.flink', name: 'flink-java', version: '1.4.1'
    compile group: 'org.apache.flink', name: 'flink-streaming-java_2.11', version: '1.4.1'
    compile group: 'org.apache.flink', name: 'flink-clients_2.11', version: '1.4.1'

    compile group: 'org.apache.flink', name: 'flink-connector-kafka-0.11_2.11', version: '1.4.1'
    compile group: 'org.apache.flink', name: 'flink-metrics-dropwizard', version: '1.4.1'
    compile group: 'org.apache.flink', name: 'flink-statebackend-rocksdb_2.11', version: '1.4.1'
    compile group: 'org.apache.flink', name: 'flink-avro', version: '1.4.1'

    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.9.2'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.2'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.9.2'
```
